# Generated by Django 2.2 on 2021-04-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='profile_image',
        ),
    ]
