# Generated by Django 2.2 on 2021-04-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210427_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='profile_pics/'),
        ),
    ]
